Repository charmbracelet/bubbletea, pull requests merged in 2022-01, with the labels that each got.

#185 Fix list-default example
  examples/list-default/main.go
Labels: bug

#189 Rename termdbms and add gh-prs to BubbleTea-powered programs
  README.md
Labels: documentation

#180 fix(tea): allocate msgs channel in constructor
  tea.go
Labels: bug

#198 chore: dependabot, go mod tidy, update bubbles
  .github/dependabot.yml
  examples/go.mod
  examples/go.sum
Labels: enhancement

#205 Fix source link in Commands tutorial
  tutorials/commands/README.md
Labels: documentation
