Repository charmbracelet/bubbletea, pull requests merged in 2022-08, with the labels that each got.

#275 Doc: Add `Noted` to README.md
  README.md
Labels: documentation

#385 Add https://github.com/MicheleFiladelfia/mandelbrot-cli to Bubble Tea in the Wild
  README.md
Labels: documentation

#394 Composable view
  examples/composable-views/main.go
Labels: documentation

#348 docs: add debounce example
  examples/debounce/main.go
Labels: documentation

#426 docs: fix typo
  exec.go
Labels: documentation

#428 keys: properly support the alt modifier
  key.go
  key_test.go
Labels: bug

#415 feat: add `Sequence` command for running commands in order
  commands.go
  examples/sequence/main.go
  tea.go
Labels: enhancement
