Repository charmbracelet/bubbletea, pull requests merged in 2022-10, with the labels that each got.

#396 fix: key bindings for urxvt, add home/end combinations
  key.go
Labels: bug, enhancement

#467 fix: properly skip over unrecognized CSI sequences.
  key.go
  key_test.go
Labels: bug

#477 Fix typo
  commands.go
Labels: documentation

#482 feat: add tea.ShowCursor, complementing tea.HideCursor
  screen.go
  tea.go
Labels: enhancement

#483 fix: don't access output from outside renderer
  tea.go
  tty.go
Labels: bug

#487 fix: force repaint after clearing the screen
  standard_renderer.go
Labels: bug

#488 fix: don't try to set alt screen when already in desired mode
  standard_renderer.go
Labels: bug

#496 fix(key): recover the insert key
  key.go
  key_test.go
Labels: bug

#503 feat: make signal handler optional
  options.go
  options_test.go
  tea.go
Labels: enhancement

#507 fix: close input on shutdown whenever possible
  tea.go
Labels: bug

#479 Update Program.Start docs to indicate it's a blocking operation
  tea.go
Labels: documentation

#512 test: add batchMsg test
  tea_test.go
Labels: enhancement

#513 test: add sequenceMsg test
  tea_test.go
Labels: enhancement

#514 test: exec returning an error for invalid and failing commands
  exec_test.go
Labels: enhancement

#515 test: add screen manipulation tests
  screen_test.go
Labels: enhancement

#519 fix: prevent double repaint when restoring terminal
  tea.go
Labels: bug

#525 fix: timeout when waiting for CancelReader
  tea.go
  tty.go
Labels: bug

#526 Spelling
  commands.go
  examples/debounce/main.go
  examples/pager/artichoke.md
  examples/pipe/main.go
  exec.go
  screen.go
  tea.go
Labels: documentation

#517 fix: restoreTerminalState resets mouse handling state
  screen_test.go
  tea.go
  tty.go
Labels: bug

#506 fix: kill should result in Start returning an error
  tea.go
  tea_test.go
Labels: bug

#501 fix: Fixup code in one more thing about commands tutorial section
  tutorials/commands/README.md
Labels: documentation

#531 feat: support ctrl+page up/down keys
  key.go
Labels: enhancement

#534 fix: lock mutex before checking altscreen state
  standard_renderer.go
Labels: bug

#535 fix: also lock mutex when accessing state read-only
  standard_renderer.go
Labels: bug

#530 fix: ensure a final render before a clean shutdown
  tea.go
Labels: bug

#539 fix: don't block in Send after shutdown
  tea.go
  tea_test.go
Labels: bug

#548 fix: don't delay messages behind a long command
  tea.go
Labels: bug

#533 fix: prevent renderer from overflowing available height
  standard_renderer.go
Labels: bug

#565 fix: restore Windows console mode on shutdown
  tea.go
Labels: bug

#541 fix: detect terminal size after exec
  signals_unix.go
  signals_windows.go
  tea.go
  tty.go
Labels: bug

#114 made "batchMsg" public since it should be
  commands.go
  commands_test.go
  tea.go
  tea_test.go
Labels: enhancement

#537 fix: maintain cursor visibility across altscreen state switch
  screen_test.go
  standard_renderer.go
Labels: bug

#571 feat: tea.WithContext ProgramOption to supply a context
  options.go
  tea.go
  tea_test.go
Labels: enhancement

#575 docs: picture tag is causing display issues
  README.md
Labels: documentation

#576 docs: clean up readme
  README.md
Labels: documentation

#586 fix: pass actual stdout's fd to command
  exec.go
Labels: bug
