Repository charmbracelet/bubbletea, pull requests merged in 2022-09, with the labels that each got.

#423 Support linux console F1-F5
  key.go
Labels: bug

#422 Fix 1-indexing when entering alt screen
  tea.go
Labels: bug

#418 Support the insert key
  key.go
Labels: enhancement

#454 fix: off-by-one error in spinner example
  examples/spinners/main.go
Labels: bug

#444 Fixes for examples/progress-download
  examples/progress-download/main.go
  examples/progress-download/tui.go
Labels: bug

#463 docs: clean up and re-order 'Bubble Tea in the Wild'
  README.md
Labels: documentation

#464 fix: wait for read-loop to finish before spawning child process
  tea.go
  tty.go
Labels: bug
