Repository charmbracelet/bubbletea, pull requests merged in 2022-02, with the labels that each got.

#217 feat: tea.Batch returns nil if all cmds are nil
  commands_test.go
  tea.go
Labels: enhancement

#221 Use termenv's EnvColorProfile, which respects NO_COLOR and CLICOLOR_FORCE env vars
  examples/altscreen-toggle/main.go
  examples/views/main.go
Labels: enhancement

#223 Simplify send-msg example
  examples/send-msg/main.go
Labels: documentation

#215 Support receiving batched mouse events
  key.go
  key_test.go
  mouse.go
  mouse_test.go
  tea.go
Labels: bug

#228 fix: don't check terminal size if we're not writing to a terminal
  tea.go
Labels: bug

#229 chore: bump lipgloss and termenv
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  tutorials/go.sum
Labels: dependencies

#242 ci: update golangci-lint-action to v3
  .github/workflows/lint-soft.yml
  .github/workflows/lint.yml
Labels: dependencies
