Repository charmbracelet/bubbletea, pull requests merged in 2023-03, with the labels that each got.

#685 fix: renderer only stops once
  standard_renderer.go
Labels: bug

#686 fix: stop renderer before launching a child process.
  standard_renderer.go
  tea.go
Labels: bug

#389 docs: issue template
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/config.yml
Labels: documentation

#692 feat: LogToFileWith
  logging.go
Labels: enhancement

#700 chore: bump console dep
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  tutorials/go.mod
  tutorials/go.sum
Labels: dependencies
