Repository charmbracelet/bubbletea, pull requests merged in 2024-02, with the labels that each got.

#397 feat: bracketed paste
  examples/simple/testdata/TestApp.golden
  key.go
  key_sequences.go
  key_test.go
  nil_renderer.go
  options.go
  options_test.go
  renderer.go
  screen.go
  screen_test.go
  standard_renderer.go
  tea.go
  tty.go
Labels: enhancement

#913 Add support for z/OS
  signals_unix.go
  tty_unix.go
Labels: enhancement

#916 feat: update bubbles, use go 1.18
  .github/workflows/build.yml
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  tutorials/go.mod
  tutorials/go.sum
Labels: dependencies

#490 Support multiline tea.Println() messages
  standard_renderer.go
Labels: triage

#802 chore: start program with alt screen instead of init
  examples/list-fancy/main.go
Labels: documentation

#878 feat: support windows console input buffer
  examples/go.mod
  examples/go.sum
  go.mod
  go.sum
  inputreader_other.go
  inputreader_windows.go
  key.go
  key_other.go
  key_test.go
  key_windows.go
  tty.go
  tutorials/go.mod
  tutorials/go.sum
Labels: triage
